import { z } from "zod";
import { baseProcedure } from "~/server/trpc/main";
import { authenticateUser } from "~/server/utils/auth";

export const getRoleTemplates = baseProcedure
  .input(
    z.object({
      token: z.string(),
    })
  )
  .query(async ({ input }) => {
    await authenticateUser(input.token);

    // Define role templates for common production positions
    const templates = [
      {
        id: "director",
        name: "Director",
        category: "Creative",
        description: "Creative lead responsible for overall artistic vision and scene execution",
        recommendedPermissions: [
          "manage_scenes",
          "view_scenes",
          "edit_scene_details",
          "manage_scene_scheduling",
          "mark_scene_complete",
          "manage_timers",
          "view_team",
          "view_team_contact_info",
          "view_reports",
          "export_reports",
          "view_shows",
          "view_production_houses",
          "send_announcements",
          "view_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "manage_actors",
          "view_actors",
          "manage_character_roles",
          "assign_actors_to_characters",
          "view_crew",
          "view_departments",
          "view_positions",
          "view_calendar",
          "check_conflicts",
          "edit_own_profile",
        ],
      },
      {
        id: "first-ad",
        name: "1st Assistant Director",
        category: "Production",
        description: "Manages day-to-day production operations, scheduling, and on-set logistics",
        recommendedPermissions: [
          "manage_scenes",
          "view_scenes",
          "edit_scene_details",
          "manage_scene_scheduling",
          "mark_scene_complete",
          "manage_timers",
          "view_team",
          "view_team_contact_info",
          "manage_reports",
          "view_reports",
          "export_reports",
          "view_shows",
          "assign_users_to_shows",
          "view_production_houses",
          "send_announcements",
          "view_announcements",
          "manage_announcements",
          "send_messages",
          "view_messages",
          "manage_call_sheets",
          "view_call_sheets",
          "generate_call_sheets",
          "distribute_call_sheets",
          "view_actors",
          "assign_actors_to_characters",
          "view_crew",
          "assign_crew_positions",
          "manage_crew_availability",
          "view_departments",
          "view_positions",
          "manage_calendar",
          "view_calendar",
          "manage_shooting_days",
          "check_conflicts",
          "edit_own_profile",
        ],
      },
      {
        id: "second-ad",
        name: "2nd Assistant Director",
        category: "Production",
        description: "Assists 1st AD with scheduling, call sheets, and cast/crew coordination",
        recommendedPermissions: [
          "view_scenes",
          "manage_scene_scheduling",
          "view_team",
          "view_team_contact_info",
          "view_reports",
          "view_shows",
          "view_production_houses",
          "send_announcements",
          "view_announcements",
          "send_messages",
          "view_messages",
          "manage_call_sheets",
          "view_call_sheets",
          "generate_call_sheets",
          "distribute_call_sheets",
          "view_actors",
          "view_crew",
          "manage_crew_availability",
          "view_departments",
          "view_positions",
          "view_calendar",
          "check_conflicts",
          "edit_own_profile",
        ],
      },
      {
        id: "production-coordinator",
        name: "Production Coordinator",
        category: "Production",
        description: "Handles administrative tasks, communications, and production logistics",
        recommendedPermissions: [
          "view_scenes",
          "view_team",
          "view_team_contact_info",
          "view_reports",
          "export_reports",
          "view_shows",
          "view_production_houses",
          "manage_production_house_members",
          "send_announcements",
          "view_announcements",
          "manage_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "distribute_call_sheets",
          "view_actors",
          "view_crew",
          "view_departments",
          "view_positions",
          "view_calendar",
          "edit_own_profile",
        ],
      },
      {
        id: "script-supervisor",
        name: "Script Supervisor",
        category: "Creative",
        description: "Maintains continuity and tracks scene coverage and takes",
        recommendedPermissions: [
          "view_scenes",
          "edit_scene_details",
          "mark_scene_complete",
          "view_team",
          "view_reports",
          "export_reports",
          "view_shows",
          "view_production_houses",
          "view_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "view_actors",
          "view_crew",
          "view_calendar",
          "edit_own_profile",
        ],
      },
      {
        id: "dop",
        name: "Director of Photography",
        category: "Technical",
        description: "Head of camera and lighting departments, responsible for visual look",
        recommendedPermissions: [
          "view_scenes",
          "edit_scene_details",
          "view_team",
          "view_team_contact_info",
          "view_reports",
          "view_shows",
          "view_production_houses",
          "view_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "view_crew",
          "view_departments",
          "view_positions",
          "view_calendar",
          "edit_own_profile",
        ],
      },
      {
        id: "production-designer",
        name: "Production Designer",
        category: "Creative",
        description: "Oversees art department and overall visual design of production",
        recommendedPermissions: [
          "view_scenes",
          "edit_scene_details",
          "view_team",
          "view_team_contact_info",
          "view_reports",
          "view_shows",
          "view_production_houses",
          "view_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "view_crew",
          "view_departments",
          "view_positions",
          "view_calendar",
          "edit_own_profile",
        ],
      },
      {
        id: "line-producer",
        name: "Line Producer",
        category: "Production",
        description: "Manages budget, schedule, and overall production logistics",
        recommendedPermissions: [
          "manage_scenes",
          "view_scenes",
          "manage_scene_scheduling",
          "manage_team",
          "view_team",
          "approve_team_members",
          "view_team_contact_info",
          "manage_reports",
          "view_reports",
          "export_reports",
          "configure_report_automation",
          "manage_shows",
          "view_shows",
          "assign_users_to_shows",
          "view_production_houses",
          "manage_production_house_members",
          "view_company_settings",
          "send_announcements",
          "view_announcements",
          "manage_announcements",
          "send_messages",
          "view_messages",
          "manage_call_sheets",
          "view_call_sheets",
          "generate_call_sheets",
          "distribute_call_sheets",
          "view_actors",
          "manage_crew",
          "view_crew",
          "assign_crew_positions",
          "manage_crew_availability",
          "manage_departments",
          "view_departments",
          "manage_positions",
          "view_positions",
          "manage_calendar",
          "view_calendar",
          "manage_shooting_days",
          "check_conflicts",
          "edit_own_profile",
        ],
      },
      {
        id: "casting-director",
        name: "Casting Director",
        category: "Creative",
        description: "Manages casting process and actor assignments",
        recommendedPermissions: [
          "view_scenes",
          "view_team",
          "view_team_contact_info",
          "view_reports",
          "view_shows",
          "view_production_houses",
          "view_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "manage_actors",
          "view_actors",
          "manage_character_roles",
          "assign_actors_to_characters",
          "view_calendar",
          "edit_own_profile",
        ],
      },
      {
        id: "production-assistant",
        name: "Production Assistant",
        category: "Production",
        description: "Entry-level support role with basic access to production information",
        recommendedPermissions: [
          "view_scenes",
          "view_team",
          "view_reports",
          "view_shows",
          "view_production_houses",
          "view_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "view_actors",
          "view_crew",
          "view_departments",
          "view_positions",
          "view_calendar",
          "edit_own_profile",
        ],
      },
      {
        id: "department-head",
        name: "Department Head",
        category: "Technical",
        description: "Leads a specific department (Camera, Sound, Art, etc.)",
        recommendedPermissions: [
          "view_scenes",
          "edit_scene_details",
          "view_team",
          "view_team_contact_info",
          "view_reports",
          "view_shows",
          "view_production_houses",
          "view_announcements",
          "send_messages",
          "view_messages",
          "view_call_sheets",
          "view_crew",
          "assign_crew_positions",
          "view_departments",
          "view_positions",
          "view_calendar",
          "edit_own_profile",
        ],
      },
      {
        id: "studio-executive",
        name: "Studio Executive",
        category: "Administrative",
        description: "Oversight role with view access to reports and high-level information",
        recommendedPermissions: [
          "view_scenes",
          "view_team",
          "view_reports",
          "export_reports",
          "view_shows",
          "approve_shows",
          "view_production_houses",
          "view_company_settings",
          "view_announcements",
          "view_call_sheets",
          "view_actors",
          "view_crew",
          "view_departments",
          "view_positions",
          "view_calendar",
          "edit_own_profile",
        ],
      },
    ];

    return {
      templates,
      categories: ["Creative", "Production", "Technical", "Administrative"],
    };
  });
